title: "Обзор LLM-инструментов"
description: ""
theme: ""

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
